application: gae-webapp2-base
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:

# if you have robots.txt
- url: /robots\.txt$
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always

# directly serve favicon
- url: /favicon\.ico$
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

# general static path
- url: /static
  static_dir: static
  secure: always

# flask handler
- url: /.*
  script: main.app
  secure: always

skip_files:
- ^(.*/)?.*\.pyc$
- ^(.*/)?\..*$
- ^app\.yaml$
- ^LICENSE$
- ^get_requirements\.py$
- ^requirements\.txt$
- ^libs/.*/
